---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: application-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5
       max-wait-millis: 200 
mybatis:
  config-locations: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lsx.entity
  mapper-locations: classpath:mybatis/mappers/**/*.xml
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka.com:7001/eureka/
  instance:
     prefer-ip-address: true
     instance-ip: provider-dept8001
     
info:
   appname: spring-cloud-provider-dept
   company-name: com.lsx
   build-artifactId: $project.artifactId$
   build-version: $project.version$
   
---

server:
  port: 8002

spring:
  profiles: test
  application:
    name: application-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5
       max-wait-millis: 200
          
mybatis:
  config-locations: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lsx.entity
  mapper-locations: classpath:mybatis/mappers/**/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka02.com:7002/eureka/
  instance:
     prefer-ip-address: true
     instance-ip: provider-dept8002
     
info:
   appname: spring-cloud-provider-dept
   company-name: com.lsx
   build-artifactId: $project.artifactId$
   build-version: $project.version$



